// <auto-generated />
using ArawanMarbleApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArawanMarbleApi.Migrations
{
    [DbContext(typeof(Ara56nmarblecomContext))]
    partial class Ara56nmarblecomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("qweqwe")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArawanMarbleApi.Models.Customer", b =>
                {
                    b.Property<int>("Customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customerid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customerid"));

                    b.Property<string>("Customeremail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customeremail");

                    b.Property<string>("Customermessage")
                        .HasColumnType("text")
                        .HasColumnName("customermessage");

                    b.Property<string>("Customername")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customername");

                    b.Property<string>("Customersubject")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("customersubject");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("Customerid")
                        .HasName("PK__customer__B61ED7F57451DEB7");

                    b.ToTable("customers", "qweqwe");
                });

            modelBuilder.Entity("ArawanMarbleApi.Models.Product", b =>
                {
                    b.Property<int>("Productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Productid"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Productimg")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("productimg");

                    b.Property<string>("Productname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("productname");

                    b.HasKey("Productid")
                        .HasName("PK__products__2D172D32E28A3E37");

                    b.ToTable("products", "qweqwe");
                });

            modelBuilder.Entity("ArawanMarbleApi.Models.Project", b =>
                {
                    b.Property<int>("Projectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("projectid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Projectid"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Projectimg")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("projectimg");

                    b.Property<string>("Projectname")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("projectname");

                    b.Property<string>("Projectplace")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("projectplace");

                    b.HasKey("Projectid")
                        .HasName("PK__projects__11EC39DD7720BDC2");

                    b.ToTable("projects", "qweqwe");
                });

            modelBuilder.Entity("ArawanMarbleApi.Models.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Userid"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("Userid")
                        .HasName("PK__users__CBA1B25754546766");

                    b.HasIndex(new[] { "Username" }, "UQ__users__F3DBC5724A16B652")
                        .IsUnique();

                    b.ToTable("users", "qweqwe");
                });
#pragma warning restore 612, 618
        }
    }
}
